spring:
  jpa:
    hibernate:
      ddl-auto:update
  jackson:
    serialization:
      INDENT_OUTPUT: true

application:
  jwt:
    secretKey: LXJeSj35XNQbds8e4ziZZfiFvl59AzSPddshLMM1WOFvS0H1bl2XySglkB5U
    tokenPrefix: Bearer
    tokenExpirationAfterDays: 14